"""The dreams themselves.

Fourteen places, each generated by its own algorithm because each is built out
of a different idea.  The pink world is a maze; the number world is a
scattering of monuments; the star ocean is mostly impassable and has to have
its walkable parts drawn as a network.  Sharing one generator between them
would make them feel like one game with fourteen skins, which is the failure
mode this whole project is trying to avoid.

Common rules, applied everywhere:

* the map loops on both axes
* landmarks are few and far apart, and the space between them is empty
* nothing is placed against an invisible border, because there isn't one
"""

from __future__ import annotations

import math
import random
import zlib
from dataclasses import dataclass, field

from ..art.chipsets import ChipsetBuild
from ..art.sheets import BUILDERS
from .. import maps
from ..maps import SCROLL_BOTH, SCROLL_NONE, Map, MapInfo
from . import gen, layout
from .gen import MazeSpec, Placer
from .layout import Field, Zone, repair_connectivity, solid_ids
from .rooms import Furnisher, Room, avenue, back_wall, corners, facing_pair, ring, spiral_out


@dataclass
class World:
    """One generated place, ready to have events hung on it."""
    key: str
    title: str
    map_id: int
    chipset_id: int
    chipset: ChipsetBuild
    map: Map
    music: str
    spawn: tuple[int, int]
    placer: Placer
    landmarks: dict[str, list[tuple[int, int]]] = field(default_factory=dict)
    tint: tuple[int, int, int, int] = (100, 100, 100, 100)
    overlay: str | None = None
    overlay_opacity: int = 0
    npcs: list[str] = field(default_factory=list)
    plan: object | None = None    # the carved layout, for events
    rooms: list = field(default_factory=list)

    def spot(self, rng: random.Random, **kwargs) -> tuple[int, int]:
        return gen.free_spot(self.map, self.placer, rng, **kwargs)


# Colour grading per world, as a screen tint: (red, green, blue, saturation),
# where 100 is neutral and the range is 0..200.  This is the single strongest
# tool the engine gives for making a place feel a particular way before the
# player has consciously registered why.
TINTS: dict[str, tuple[int, int, int, int]] = {
    "room": (104, 100, 94, 96),          # warm, slightly faded
    "nexus": (86, 88, 108, 78),          # cold, desaturated, low
    "pink": (110, 96, 102, 104),         # pushed towards its own pink
    "numbers": (96, 104, 102, 92),       # clinical
    "blocks": (106, 102, 108, 110),      # bright nursery
    "stairs": (92, 96, 116, 88),         # cold height
    "sand": (108, 106, 98, 74),          # bleached
    "faces": (100, 108, 94, 102),        # green and warm
    "hands": (98, 102, 96, 86),          # stone
    "checker": (100, 100, 102, 70),      # nearly monochrome
    "toys": (110, 104, 96, 112),         # saturated childhood
    "neon": (96, 100, 118, 128),         # electric
    "umbrellas": (94, 102, 106, 92),     # damp
    "stars": (90, 94, 122, 96),          # deep blue
}

# The screen overlay each world wears, and how strongly.  Transparency is
# 0..100 where 100 is invisible, so these are all whispers.
OVERLAYS: dict[str, tuple[str, int]] = {
    "room": ("Grain", 88),
    "nexus": ("Vignette", 62),
    "pink": ("HazePink", 90),
    "numbers": ("Grain", 92),
    "blocks": ("Dust", 86),
    "stairs": ("VignetteSoft", 70),
    "sand": ("DustB", 78),
    "faces": ("Shaft", 84),
    "hands": ("VignetteSoft", 76),
    "checker": ("Grain", 90),
    "toys": ("HazeGold", 88),
    "neon": ("Scanline", 74),
    "umbrellas": ("HazePink", 92),
    "stars": ("Dust", 80),
}

MUSIC: dict[str, str] = {
    "room": "Room", "nexus": "Nexus", "pink": "Pink", "numbers": "Numbers",
    "blocks": "Blocks", "stairs": "Stairs", "sand": "Sand", "faces": "Faces",
    "hands": "Hands", "checker": "Checker", "toys": "Toys", "neon": "Neon",
    "umbrellas": "Umbrellas", "stars": "Stars",
}

TITLES: dict[str, str] = {
    "room": "the room",
    "nexus": "the doors",
    "pink": "brick",
    "numbers": "counting",
    "blocks": "the nursery",
    "stairs": "up",
    "sand": "nothing much",
    "faces": "the grove",
    "hands": "the field",
    "checker": "squares",
    "toys": "small",
    "neon": "scrawl",
    "umbrellas": "no rain",
    "stars": "the shallows",
}

# Which door in the nexus leads where, in the order they stand.
DREAM_ORDER = ["pink", "numbers", "blocks", "stairs", "sand", "faces", "hands",
               "checker", "toys", "neon", "umbrellas", "stars"]

WORLD_ORDER = ["room", "nexus", *DREAM_ORDER]


def _new(key: str, map_id: int, width: int, height: int, *,
         loop: bool = True) -> tuple[World, ChipsetBuild, random.Random]:
    build = BUILDERS[key]()
    chipset_id = WORLD_ORDER.index(key) + 1
    m = Map(width, height, chipset_id,
            scroll_type=SCROLL_BOTH if loop else SCROLL_NONE,
            fill=build.tiles["ground"])
    overlay, opacity = OVERLAYS[key]
    world = World(key=key, title=TITLES.get(key, key), map_id=map_id,
                  chipset_id=chipset_id, chipset=build, map=m,
                  music=MUSIC.get(key, "(OFF)"), spawn=(width // 2, height // 2),
                  placer=Placer(width, height), tint=TINTS[key],
                  overlay=overlay, overlay_opacity=opacity)
    # crc32, not hash(): Python randomises string hashing per process, so
    # hash() would generate a different world on every single build and
    # nothing could be validated or reproduced.
    return world, build, random.Random(zlib.crc32(key.encode()))


# --- the two places that are not dreams --------------------------------------

def build_room(map_id: int) -> World:
    """A small room with one bed, one door and one window.  Does not loop.

    Four walls, not one.  A room with a single back wall gives furniture only
    one place to stand, and everything lines up along it like a showroom — so
    the near and side walls are real, and the furniture is grouped the way a
    person's things actually collect: the sleeping corner on one side, the
    everything-else corner on the other, and the middle left alone.
    """
    world, cs, rng = _new("room", map_id, 21, 17, loop=False)
    m, t = world.map, cs.tiles

    m.fill_rect(0, 0, m.width, m.height, t["ground"])

    # the back wall, three tiles deep, and the other three one tile deep
    for x in range(m.width):
        gen.stamp(m, cs.obj("wall"), x, 0)
    for y in range(3, m.height):
        m.set_lower(0, y, t["skirt"])
        m.set_lower(m.width - 1, y, t["skirt"])
    for x in range(m.width):
        m.set_lower(x, m.height - 1, t["skirt"])

    # -- the sleeping corner, left
    gen.stamp(m, cs.obj("bed"), 1, 3)
    gen.stamp(m, cs.obj("television"), 1, 11)

    # -- the rest of a life, right.  Spread down the wall rather than lined up
    # along the back one, so crossing the room passes each of them in turn.
    gen.stamp(m, cs.obj("wardrobe"), 18, 3)
    gen.stamp(m, cs.obj("desk"), 18, 8)
    gen.stamp(m, cs.obj("mirror"), 18, 12)

    # -- the back wall itself: the door you cannot use, and the window
    gen.stamp(m, cs.obj("door"), 9, 0)
    gen.stamp(m, cs.obj("window"), 5, 1)
    m.set_upper(14, 1, t["lamp"])

    # The rug sits in front of the television, not filling a corner.
    m.fill_rect(5, 9, 6, 4, t["rug"])

    world.landmarks = {
        "bed": [(1, 3)], "desk": [(18, 8)], "wardrobe": [(18, 3)],
        "television": [(1, 11)], "mirror": [(18, 12)], "window": [(5, 1)],
        "door": [(9, 0)],
    }
    world.spawn = (10, 11)
    world.npcs = []
    return world


def build_nexus(map_id: int) -> World:
    """A dark loop with twelve doors standing in it, and nothing else."""
    world, cs, rng = _new("nexus", map_id, 44, 34)
    m, t = world.map, cs.tiles
    gen.fill_ground(m, t, rng, second_chance=0.14, decal_chance=0.006)

    # The doors stand in a ring, so that walking the loop passes all of them
    # and arriving back at the first one feels like an answer.
    import math
    doors = []
    for index in range(12):
        angle = -math.pi / 2 + index * math.tau / 12
        x = int(m.width / 2 + math.cos(angle) * 15) - 1
        y = int(m.height / 2 + math.sin(angle) * 11) - 1
        gen.stamp(m, cs.obj("door"), x, y)
        world.placer.mark(x, y, 2, 3, f"door_{DREAM_ORDER[index]}")
        doors.append((x, y))
        gen.patch(m, t["glow"], x + 1, y + 3, 2.4, rng, ragged=0.2)

    gen.stamp(m, cs.obj("mirror"), m.width // 2 - 1, 2)
    gen.stamp(m, cs.obj("bench"), m.width // 2 - 1, m.height - 6)
    for lx, ly in ((6, 6), (m.width - 8, 6), (6, m.height - 9),
                   (m.width - 8, m.height - 9)):
        gen.stamp(m, cs.obj("lamp"), lx, ly)
        gen.patch(m, t["glow"], lx, ly + 3, 3.0, rng, ragged=0.25)

    world.landmarks = {
        "doors": doors,
        "mirror": [(m.width // 2 - 1, 2)],
        "bench": [(m.width // 2 - 1, m.height - 6)],
    }
    # Arriving in the dead centre of the ring shows nothing at all — the doors
    # are eleven tiles out and the screen is fifteen tall.  Standing in front
    # of the first one instead means the hub opens on a door, and the ring
    # curves away to either side of it.
    world.spawn = (doors[0][0] + 1, doors[0][1] + 3)
    world.npcs = ["keeper", "sleeper", "cloud_ladder"]
    return world


# --- the dreams --------------------------------------------------------------

def build_pink(map_id: int) -> World:
    """PINK BRICK.

    theme      a building that is only corridors and rooms, all of it brick
    feeling    hypnosis; the comfort of somewhere you have already been
    layout     a lattice of octagonal chambers joined by three-wide corridors
    rule       every chamber looks like the last one, and one of them does not
    """
    world, cs, rng = _new("pink", map_id, 132, 124)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    # Corridor-dominant: you are almost always in a hallway, and the rooms are
    # things you glance into on the way past.  That is what makes a building
    # feel endless rather than merely large.
    rooms = layout.warren(fld, rng, halls=14, cells_per_hall=5,
                          cell_size=(13, 11), hall_width=3)
    # Second constraint: compression.  Narrow halls open without warning into
    # something stadium-sized for one screen, then close again.
    blowouts = layout.compress(fld, rng, rooms, blowouts=5, size=(34, 28))
    rooms += blowouts
    hall_start = (rooms[0].cx, rooms[0].cy)
    # Rooms embedded in the brick that can be seen and never entered.
    sealed = layout.glimpsed_rooms(fld, rng, count=16, size=(9, 7))
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(3)
    layout.seal_off(fld, sealed, thickness=2)
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)
    for zone in sealed:
        layout.carpet(m, fld, zone, t, rng, "full")

    # Each chamber gets one thing in the middle, and nothing else.
    for index, zone in enumerate(rooms):
        if index % 3 == 0:
            gen.stamp_centered(m, cs.obj("arch"), zone.cx, zone.cy)
        elif index % 3 == 1:
            for spot in layout.zone_spots(fld, zone, rng, 2, w=1, h=3, pad=1):
                gen.stamp(m, cs.obj("column"), *spot)
        else:
            gen.stamp_centered(m, cs.obj("niche"), zone.cx, zone.cy)

    world.plan = fld
    world.landmarks = {"rooms": [(z.cx, z.cy) for z in rooms],
                       "hall": [hall_start]}
    world.spawn = (rooms[0].cx, rooms[0].cy)
    world.npcs = ["measurer", "brick_child"]
    return world


def build_numbers(map_id: int) -> World:
    """COUNTING.

    theme      a landscape assembled out of digits, at monument scale
    feeling    being audited by something that has forgotten what it counts
    layout     stepped terraces in a black void, joined end to end in a ring
    rule       every terrace carries one number, and the numbers do not add up
    """
    world, cs, rng = _new("numbers", map_id, 150, 138)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    shelves = layout.terraces(fld, rng, count=22, size=(24, 15),
                              corridor_width=3)
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(3)
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)

    digits = [cs.obj(f"digit_{d}") for d in (0, 1, 3, 5, 7, 9)]
    signs = [cs.obj(f"sign_{k}") for k in ("plus", "minus", "equals")]
    # Second constraint: every terrace is made of a different material.  The
    # shape repeats; the substance never does, so crossing one is an event.
    materials = ["full", "checker", "lattice", "rings", "stripe", "corners",
                 "cross", "border"]
    for index, zone in enumerate(shelves):
        layout.carpet(m, fld, zone, t, rng, materials[index % len(materials)])
        run = rng.randint(2, 3)
        base_x = zone.cx - (run * 4) // 2
        base_y = zone.cy - 3
        for step in range(run):
            gx = base_x + step * 4
            if not fld.open_space(gx, base_y, 3, 6, 0):
                continue
            gen.stamp(m, cs.obj("plinth"), gx, base_y + 4)
            gen.stamp(m, digits[rng.randrange(len(digits))], gx, base_y)
            if step < run - 1:
                gen.stamp(m, signs[rng.randrange(len(signs))], gx + 3,
                          base_y + 2)

    world.plan = fld
    world.landmarks = {"terraces": [(z.cx, z.cy) for z in shelves]}
    world.spawn = (shelves[0].cx, shelves[0].cy + 5)
    world.npcs = ["counter", "zero"]
    return world


def build_blocks(map_id: int) -> World:
    """THE NURSERY.

    theme      a city built out of children's blocks, at city scale
    feeling    playing in a room you have grown too big for
    layout     rectangular yards in a grid, walled with stacked block ends
    rule       the blocks are architecture, and one of them is the wrong size
    """
    world, cs, rng = _new("blocks", map_id, 146, 130)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    # Slabs floating in nothing, joined by narrow bridges: the gaps are the
    # point, because you can see where you are going long before you can work
    # out how to get there.
    yards = layout.platforms(fld, rng, count=28, size=(15, 13), bridge=3,
                             shape="rect")
    # Second constraint: no two slabs share a geometry, so the world reads as
    # twenty-eight decisions rather than one rule applied twenty-eight times.
    layout.vary_zones(yards, rng)
    for zone in yards:
        fld.carve(zone)
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(3)
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)

    blocks = [cs.obj(f"block_{i}") for i in range(4)]
    # Scale refuses to settle: some yards are furnished as toy rooms, some as
    # a single enormous object, some are left almost bare.
    for index, zone in enumerate(yards):
        layout.carpet(m, fld, zone, t, rng,
                      ("full", "checker", "rings", "lattice",
                       "border")[index % 5])
        # a tower in the middle of the yard, and small blocks around the edge
        stack = rng.randint(1, 3)
        for level in range(stack):
            gen.stamp(m, blocks[rng.randrange(4)], zone.cx - 1,
                      zone.cy - 1 + level * 3)
        for spot in layout.zone_spots(fld, zone, rng, 5, w=1, h=1, pad=1):
            gen.stamp(m, cs.obj("block_tiny"), *spot)
        for spot in layout.zone_spots(fld, zone, rng, 2, w=2, h=2, pad=1):
            gen.stamp(m, cs.obj("ball"), *spot)
        layout.glow_floor(m, fld, zone, t, f"anim_{index % 3}",
                          ring(zone, 5, inset=3))

    big = yards[len(yards) // 2]
    gen.stamp(m, cs.obj("block_huge"), big.cx - 2, big.cy - 2)

    world.plan = fld
    world.landmarks = {"yards": [(z.cx, z.cy) for z in yards],
                       "huge": [(big.cx, big.cy)]}
    world.spawn = (yards[0].cx, yards[0].cy + 5)
    world.npcs = ["stacker", "block_cat"]
    return world


def build_stairs(map_id: int) -> World:
    """UP.

    theme      a stairwell with no building around it
    feeling    vertigo without height; effort without arrival
    layout     landings strung along a ring, joined by long narrow flights
    rule       everything not stone is a drop, and the drop has no bottom
    """
    world, cs, rng = _new("stairs", map_id, 148, 134)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    landings = layout.ring_world(fld, rng, rooms=11, radius=52, size=(15, 12),
                                 shape="diamond", corridor_width=3)
    landings += layout.ring_world(fld, rng, rooms=7, radius=27, size=(13, 10),
                                  shape="diamond", corridor_width=3)
    middle = fld.carve(Zone("middle", m.width // 2, m.height // 2, 17, 13,
                            "round"))
    for zone in landings[::2]:
        fld.corridor((middle.cx, middle.cy), (zone.cx, zone.cy), width=3)
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(2)
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)

    for index, zone in enumerate(landings):
        gen.stamp(m, cs.obj("stair_up" if index % 2 else "stair_down"),
                  zone.cx - 2, zone.cy - 1)
        if index % 3 == 0:
            gen.stamp(m, cs.obj("lamp"), zone.cx + 4, zone.cy - 2)
    gen.stamp_centered(m, cs.obj("spiral"), middle.cx, middle.cy)

    world.plan = fld
    world.landmarks = {"landings": [(z.cx, z.cy) for z in landings],
                       "middle": [(middle.cx, middle.cy)]}
    world.spawn = (landings[0].cx, landings[0].cy)
    world.npcs = ["climber", "long_bird"]
    return world


def build_sand(map_id: int) -> World:
    """NOTHING MUCH.

    theme      a room so large it has weather
    feeling    the specific loneliness of being able to see very far
    layout     one enormous hall, with a few small chambers off it
    rule       the emptiness is the content; the walls are always visible
    """
    world, cs, rng = _new("sand", map_id, 150, 140)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    # One enormous room with recesses off it.  The walls stay visible in the
    # far distance and never come near you, which is the whole feeling.
    halls = layout.great_hall(fld, rng, alcoves=14, fill=0.74)
    hall, side = halls[0], halls[1:]
    # Second constraint: the hall is divided into districts internally, so the
    # space changes without the player ever passing through a door.
    districts = layout.regions(fld, rng, hall, count=8, size=(28, 22))
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(3)
    layout.paint(m, fld, t, rng=rng, decal_chance=0.004)
    layout.shade_walls(m, fld, t)

    # Each district is a *place*, not a tint.  A room this size with nothing
    # in it is a wasteland; the player never leaves the hall, so the hall has
    # to keep changing under them.
    district_styles = ["full", "lattice", "rings", "checker", "stripe",
                       "corners", "cross", "border"]
    marks = [k for k in cs.objects if k.startswith("mark_")]
    props = ["structure", "obelisk", "dead_tree", "post"]
    from .rooms import ring as _ring, avenue as _avenue, corners as _corners
    for index, region in enumerate(districts):
        layout.carpet(m, fld, region, t, rng,
                      district_styles[index % len(district_styles)])
        # a landmark anchors every other district
        if marks and index % 2 == 0:
            grid = cs.obj(marks[(index // 2) % len(marks)])
            gx, gy = region.cx - grid.cols // 2, region.cy - grid.rows // 2
            if fld.open_space(gx, gy, grid.cols, grid.rows, 1):
                gen.stamp(m, grid, gx, gy)
        # and every district is populated, in its own arrangement
        arrangement = (_ring(region, 6, inset=5) if index % 3 == 0 else
                       _avenue(region, 3, spacing=6) if index % 3 == 1 else
                       _corners(region, 5))
        for slot, (px, py) in enumerate(arrangement):
            grid = cs.obj(props[(index + slot) % len(props)])
            if fld.open_space(px, py, grid.cols, grid.rows, 1):
                gen.stamp(m, grid, px, py)
        layout.glow_floor(m, fld, region, t, f"anim_{index % 3}",
                          _ring(region, 5, inset=3))

    # Things standing in the open between the districts, so the walk across
    # the hall is never empty either.
    for step in range(26):
        angle = step * 6.28318 / 26
        radius = 0.22 + (step % 4) * 0.13
        px = int(hall.cx + math.cos(angle) * hall.w * 0.5 * radius)
        py = int(hall.cy + math.sin(angle) * hall.h * 0.5 * radius)
        grid = cs.obj(props[step % len(props)])
        if fld.open_space(px, py, grid.cols, grid.rows, 2):
            gen.stamp(m, grid, px, py)

    world.plan = fld
    world.landmarks = {"hall": [(hall.cx, hall.cy)],
                       "districts": [(z.cx, z.cy) for z in districts],
                       "alcoves": [(z.cx, z.cy) for z in side]}
    world.spawn = (hall.cx, hall.cy + 14)
    world.npcs = ["waiting_one", "sand_walker"]
    return world


def build_faces(map_id: int) -> World:
    """THE GREEN.

    theme      a town the forest grew through, without anyone switching it off
    feeling    walking home down a street that stopped being a street
    layout     a road grid, buried in solid green mass, the junctions surviving
    rule       the infrastructure is still running and nothing has been moved
    """
    world, cs, rng = _new("faces", map_id, 144, 132)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    # The street plan comes first: this was a town before it was anything else,
    # and the roads are what the forest had to grow around.
    avenues_x = [18, 52, 90, 124]
    avenues_y = [16, 50, 84, 116]
    for x in avenues_x:
        fld.long_hall(x, 0, m.height, vertical=True, width=5)
    for y in avenues_y:
        fld.long_hall(0, y, m.width, vertical=False, width=5)

    # Junctions open out into squares; the forest took the blocks between them.
    junctions = []
    for x in avenues_x:
        for y in avenues_y:
            junctions.append(fld.carve(Zone(f"junction_{x}_{y}", x, y,
                                            rng.randint(15, 23),
                                            rng.randint(13, 19),
                                            rng.choice(("rect", "octagon")))))
    # and a few clearings where the trees won outright
    glades = []
    for index in range(10):
        cx, cy = rng.randrange(m.width), rng.randrange(m.height)
        zone = fld.carve(Zone(f"glade{index}", cx, cy, rng.randint(13, 21),
                              rng.randint(11, 17), "round"))
        fld.corridor((zone.cx, zone.cy),
                     (avenues_x[index % 4], avenues_y[(index // 2) % 4]),
                     width=3)
        glades.append(zone)

    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(6)          # the green is a solid mass, not a treeline
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)

    # Lay the actual road surface back over the avenues, lane markings and all.
    for x in avenues_x:
        for y in range(m.height):
            for o in range(-2, 3):
                if fld.is_floor(x + o, y):
                    m.set_lower(x + o, y, t["kerb"] if abs(o) == 2 else
                                (t["road_line"] if o == 0 and y % 4 < 2
                                 else t["road"]))
    for y in avenues_y:
        for x in range(m.width):
            for o in range(-2, 3):
                if fld.is_floor(x, y + o):
                    m.set_lower(x, y + o, t["kerb"] if abs(o) == 2 else
                                (t["road_line"] if o == 0 and x % 4 < 2
                                 else t["road"]))

    fur = Furnisher(m, fld, cs, rng)
    # Junctions get the municipal furniture: lights on every corner, a shelter,
    # a phone box still lit, a car nobody came back for.
    street = ["traffic_light", "shelter", "phone_box", "car", "vending",
              "road_sign"]
    for index, zone in enumerate(junctions):
        layout.carpet(m, fld, zone, t, rng, "full",
                      patterns=["pattern_0", "pattern_1"])
        for slot, (px, py) in enumerate(corners(zone, 4)):
            fur.put("traffic_light", px, py, pad=0)
        for slot, (px, py) in enumerate(ring(zone, 4, inset=6)):
            fur.put(street[(index + slot) % len(street)], px, py, pad=1)
        # a tree straight through the middle of the junction
        fur.put("tree", zone.cx, zone.cy, pad=1)

    # The glades are what the town looks like once the road has gone.
    for index, zone in enumerate(glades):
        layout.carpet(m, fld, zone, t, rng, "rings")
        for px, py in ring(zone, 6, inset=4):
            fur.put("tree" if (px + py) % 3 else "tree_plain", px, py, pad=1)
        fur.put("stump", zone.cx, zone.cy, pad=1)
        layout.glow_floor(m, fld, zone, t, "anim_0", ring(zone, 4, inset=2))

    world.plan = fld
    world.landmarks = {"junctions": [(z.cx, z.cy) for z in junctions],
                       "glades": [(z.cx, z.cy) for z in glades]}
    world.spawn = (avenues_x[0], avenues_y[0])
    world.npcs = ["gardener", "seedling"]
    return world


def build_hands(map_id: int) -> World:
    """THE FIELD.

    theme      a procession nobody is walking, to somewhere nobody named
    feeling    trespassing on a rite that has been going on without you
    layout     one enormous avenue; ten courts opening off it, all different
    rule       the courts interrupt the procession, and no two interrupt it
               in the same way — one is empty, one is drowned, one is another
               avenue, one is nothing but doors
    """
    world, cs, rng = _new("hands", map_id, 150, 128)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    avenue_zone = fld.carve(Zone("avenue", m.width // 2, m.height // 2, 138, 17,
                                 "rect"))
    # Ten courts, each with its own shape, size and reason to exist.  The
    # variety *is* the world; ten identical diamonds was the old failure.
    court_plan = [
        ("circle", "round", 25, 23), ("sunken", "rect", 19, 17),
        ("raised", "octagon", 23, 19), ("inner_avenue", "rect", 33, 11),
        ("benches", "diamond", 19, 17), ("water", "round", 27, 21),
        ("doors", "rect", 21, 15), ("empty", "octagon", 29, 25),
        ("dense", "round", 21, 19), ("narrow", "rect", 13, 27),
    ]
    courts = []
    for index, (name, shape, cw, ch) in enumerate(court_plan):
        cx = 14 + index * 14
        cy = m.height // 2 + (26 if index % 2 else -26)
        zone = fld.carve(Zone(name, cx, cy, cw, ch, shape))
        fld.corridor((cx, m.height // 2), (cx, cy), width=3, bend="vh")
        courts.append((name, zone))
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(4)
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)

    fur = Furnisher(m, fld, cs, rng)
    # The avenue itself: two rows of hands facing each other the whole way,
    # so walking it always feels like passing between something.
    layout.carpet(m, fld, avenue_zone, t, rng, "stripe")
    for x in range(8, m.width - 8, 9):
        for y, pose in ((avenue_zone.cy - 6, "hand_up"),
                        (avenue_zone.cy + 3, "hand_reach")):
            if fld.open_space(x, y, 3, 4, 0):
                gen.stamp(m, cs.obj(pose), x, y)
    layout.glow_floor(m, fld, avenue_zone, t, "anim_0",
                      [(x, avenue_zone.cy) for x in range(6, m.width, 13)])

    marks = [k for k in cs.objects if k.startswith("mark_")]
    for index, (name, zone) in enumerate(courts):
        if name == "circle":
            layout.carpet(m, fld, zone, t, rng, "rings")
            if marks:
                grid = cs.obj(marks[1 % len(marks)])       # the ring of hands
                gen.stamp(m, grid, zone.cx - grid.cols // 2,
                          zone.cy - grid.rows // 2)
        elif name == "sunken":
            # a darker floor, so it reads as being below the avenue
            for dy in range(-zone.h // 2, zone.h // 2 + 1):
                for dx in range(-zone.w // 2, zone.w // 2 + 1):
                    if fld.is_floor(zone.cx + dx, zone.cy + dy):
                        m.set_lower(zone.cx + dx, zone.cy + dy, t["ground_b"])
            layout.carpet(m, fld, zone, t, rng, "checker")
            fur.put("hand_broken", zone.cx, zone.cy, pad=1)
        elif name == "raised":
            layout.carpet(m, fld, zone, t, rng, "full")
            fur.put("plinth", zone.cx, zone.cy, pad=1)
            for px, py in ring(zone, 6, inset=4):
                fur.put("hand_up", px, py, pad=1)
        elif name == "inner_avenue":
            # a court containing another avenue, at a quarter of the scale
            layout.carpet(m, fld, zone, t, rng, "stripe")
            for x in range(zone.cx - 13, zone.cx + 14, 5):
                fur.put("hand_up", x, zone.cy - 3, pad=0)
                fur.put("hand_reach", x, zone.cy + 3, pad=0)
        elif name == "benches":
            layout.carpet(m, fld, zone, t, rng, "lattice")
            for px, py in avenue(zone, 3, spacing=5):
                fur.put("plinth", px, py, pad=1)
        elif name == "water":
            for dy in range(-zone.h // 2, zone.h // 2 + 1):
                for dx in range(-zone.w // 2, zone.w // 2 + 1):
                    if fld.is_floor(zone.cx + dx, zone.cy + dy):
                        m.set_lower(zone.cx + dx, zone.cy + dy, t["anim_1"])
            fur.put("hand_reach", zone.cx, zone.cy, pad=1)
        elif name == "doors":
            layout.carpet(m, fld, zone, t, rng, "full")
            if len(marks) > 2:
                grid = cs.obj(marks[2])                    # the hand and door
                gen.stamp(m, grid, zone.cx - grid.cols // 2,
                          zone.cy - grid.rows // 2)
        elif name == "empty":
            # deliberately almost nothing, and the largest court of the ten
            layout.carpet(m, fld, zone, t, rng, "border")
        elif name == "dense":
            layout.carpet(m, fld, zone, t, rng, "full")
            for px, py in ring(zone, 8, inset=3) + corners(zone, 4):
                fur.put("hand_up" if (px + py) % 2 else "hand_broken", px, py,
                        pad=0)
        else:   # narrow: a slot too tight for the procession to turn round in
            layout.carpet(m, fld, zone, t, rng, "cross")
            for px, py in avenue(zone, 2, spacing=6):
                fur.put("hand_reach", px, py, pad=0)
        layout.glow_floor(m, fld, zone, t, f"anim_{index % 3}",
                          ring(zone, 4, inset=3))

    world.plan = fld
    world.landmarks = {"avenue": [(avenue_zone.cx, avenue_zone.cy)],
                       "courts": [(z.cx, z.cy) for _, z in courts]}
    world.spawn = (avenue_zone.cx, avenue_zone.cy)
    world.npcs = ["walking_hand", "ring_keeper"]
    return world


def build_checker(map_id: int) -> World:
    """SQUARES.

    theme      a board with the pieces taken off it
    feeling    being a piece that was left behind
    layout     square rooms on a strict grid, no jitter, no mercy
    rule       everything is square, including the parts that should not be
    """
    world, cs, rng = _new("checker", map_id, 138, 126)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    # Identical cells, exactly placed, with no variation whatsoever.  The
    # repetition is the effect: after a while you stop trusting that you moved.
    rooms = layout.strict_grid(fld, rng, cols=6, rows=5, size=(15, 13),
                               corridor_width=3)
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(3)
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)

    # the floor of each room is its own checker, offset from its neighbours
    for index, zone in enumerate(rooms):
        for dy in range(-zone.h // 2, zone.h // 2 + 1):
            for dx in range(-zone.w // 2, zone.w // 2 + 1):
                if not fld.is_floor(zone.cx + dx, zone.cy + dy):
                    continue
                block = ((dx // 4) + (dy // 4) + index) % 2
                m.set_lower(zone.cx + dx, zone.cy + dy,
                            t["ground"] if block else t["ground_b"])
        if index % 3 == 0:
            gen.stamp(m, cs.obj("house"), zone.cx - 2, zone.cy - 2)
        elif index % 3 == 1:
            gen.stamp(m, cs.obj("house_pale"), zone.cx - 2, zone.cy - 2)
        else:
            for spot in layout.zone_spots(fld, zone, rng, 3, w=1, h=4, pad=2):
                gen.stamp(m, cs.obj("pillar"), *spot)

    world.plan = fld
    world.landmarks = {"rooms": [(z.cx, z.cy) for z in rooms]}
    world.spawn = (rooms[0].cx, rooms[0].cy + 5)
    world.npcs = ["pawn", "housekeeper"]
    return world


def build_toys(map_id: int) -> World:
    """SMALL.

    theme      a toy box seen from inside, at the scale of the toys
    feeling    the exact size a child feels in a room of adults
    layout     narrow aisles between walls of stacked toys, opening into pits
    rule       nothing here is your size, and the walls are made of playthings
    """
    world, cs, rng = _new("toys", map_id, 140, 128)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    # Streets between stacks taller than you are.  The floor is continuous and
    # the masses make the shape, so the gaps read as alleys in a toy city.
    pits = layout.canyons(fld, rng, blocks=32, block_size=(13, 11), margin=5)
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(4)
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)

    crayons = [cs.obj(f"crayon_{i}") for i in range(3)]
    for index, zone in enumerate(pits):
        # crayons stand along the back wall of each pit like a skyline
        for step in range(5):
            x = zone.cx - 6 + step * 3
            y = zone.cy - zone.h // 2 + 1
            if fld.open_space(x, y, 2, 5, 0):
                gen.stamp(m, crayons[(step + index) % 3], x, y)
        gen.stamp_centered(m, cs.obj("die" if index % 2 else "rings"),
                           zone.cx, zone.cy + 3)
        for spot in layout.zone_spots(fld, zone, rng, 2, w=2, h=2, pad=1):
            gen.stamp(m, cs.obj("jack" if rng.random() < 0.5 else "die_small"),
                      *spot)

    world.plan = fld
    world.landmarks = {"pits": [(z.cx, z.cy) for z in pits]}
    # The avenue that canyons() drives through the district is guaranteed
    # walkable; a "street" zone centre may be sitting inside a toy block.
    world.spawn = (m.width // 2, m.height // 2 - 1)
    world.npcs = ["wind_up", "cone"]
    return world


def build_neon(map_id: int) -> World:
    """SCRAWL.

    theme      a black room somebody has been writing on for a very long time
    feeling    reading something addressed to you in a language you don't have
    layout     thirty octagonal chambers in black void, walls of glowing tile
    rule       the writing is on the walls, and no two rooms say the same thing
    """
    world, cs, rng = _new("neon", map_id, 152, 132)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    zones = layout.chambers(fld, rng, cols=6, rows=5, size=(20, 17),
                            shape="octagon", corridor_width=3, skip=0.06,
                            jitter=1)
    # the one big room in the middle that the whole world hangs off
    plaza = fld.carve(Zone("plaza", m.width // 2, m.height // 2, 34, 26,
                           "round"))
    for zone in zones[:6]:
        fld.corridor((plaza.cx, plaza.cy), (zone.cx, zone.cy), width=3)
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(3)
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)

    fur = Furnisher(m, fld, cs, rng)
    # Ten room kinds, dealt round-robin, so no two neighbours are furnished the
    # same and the world takes a while to repeat itself.
    kinds = ["eye", "spiral", "mouth", "arrow", "star", "mural", "eyes_ring",
             "arrows_avenue", "pair", "glowpit"]
    carpets = ["full", "lattice", "rings", "checker", "border", "stripe",
               "cross", "corners"]
    for index, zone in enumerate(zones):
        kind = kinds[index % len(kinds)]
        # every room is carpeted, and no two adjacent rooms the same way
        layout.carpet(m, fld, zone, t, rng, carpets[index % len(carpets)])
        room = Room(zone, kind)
        if kind in ("eye", "spiral", "mouth", "arrow", "star"):
            fur.put(f"scrawl_{kind}", zone.cx, zone.cy)
            room.interactables.append((zone.cx, zone.cy + 3, "", NEON_LINES[kind]))
        elif kind == "mural":
            gen.stamp(m, cs.obj(f"mural_{index % 3}"), zone.cx - 2, zone.cy - 2)
            room.interactables.append((zone.cx, zone.cy + 3, "",
                                       "it is painted on the floor, not in it."))
        elif kind == "eyes_ring":
            fur.put_many(["scrawl_eye"], ring(zone, 3, inset=5))
            layout.glow_floor(m, fld, zone, t, "anim_0", ring(zone, 6, inset=3))
        elif kind == "arrows_avenue":
            fur.put_many(["scrawl_arrow"], avenue(zone, 2, spacing=8))
            layout.glow_floor(m, fld, zone, t, "anim_2",
                              [(zone.cx, zone.cy + dy) for dy in range(-4, 5, 2)])
        elif kind == "pair":
            fur.put_many(["scrawl_mouth", "scrawl_star"], facing_pair(zone, 7))
        else:   # glowpit: no scrawl at all, just a floor that will not hold still
            layout.glow_floor(m, fld, zone, t, "anim_1", spiral_out(zone, 14))
            layout.glow_floor(m, fld, zone, t, "flow", ring(zone, 8, inset=4))
            room.interactables.append((zone.cx, zone.cy, "",
                                       "the floor is warm here."))
        world.rooms.append(room)

    # The plaza in the middle: the densest floor in the game.
    layout.carpet(m, fld, plaza, t, rng, "rings")
    gen.stamp(m, cs.obj("mural_0"), plaza.cx - 2, plaza.cy - 8)
    fur.put_many(["scrawl_spiral", "scrawl_star", "scrawl_eye"],
                 ring(plaza, 5, inset=8))
    layout.glow_floor(m, fld, plaza, t, "flow", ring(plaza, 12, inset=4))
    layout.glow_floor(m, fld, plaza, t, "anim_0", ring(plaza, 6, inset=11))
    world.rooms.append(Room(plaza, "plaza"))

    world.plan = fld
    world.landmarks = {
        "chambers": [(z.cx, z.cy) for z in zones],
        "plaza": [(plaza.cx, plaza.cy)],
        "eyes": [(z.cx, z.cy) for i, z in enumerate(zones)
                 if kinds[i % len(kinds)] == "eye"],
    }
    world.spawn = (plaza.cx, plaza.cy + 8)
    world.npcs = ["floating_eye", "scrawler"]
    repair_connectivity(m, fld, cs, world.spawn, t["ground"])
    return world


NEON_LINES = {
    "eye": "it has been open the whole time.",
    "spiral": "you lose your place halfway round.",
    "mouth": "it is not a smile, exactly.",
    "arrow": "it points at the wall behind it.",
    "star": "one of the points is longer than the others.",
}


def build_umbrellas(map_id: int) -> World:
    """NO RAIN.

    theme      shelter provided in enormous quantity, for weather that never comes
    feeling    being looked after by something that has misunderstood the job
    layout     dense clusters joined by threads a single tile wide
    rule       the canopies are the ceiling, and there is no sky above them
    """
    world, cs, rng = _new("umbrellas", map_id, 140, 128)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    groves = layout.clusters(fld, rng, count=22, blobs=6, radius=(7, 11),
                             thread=2)
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(3)
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)

    canopies = [cs.obj(f"umbrella_{i}") for i in range(3)]
    fur = Furnisher(m, fld, cs, rng)
    for index, zone in enumerate(groves):
        layout.carpet(m, fld, zone, t, rng,
                      ("rings", "full", "lattice", "checker")[index % 4])
        for spot in layout.zone_spots(fld, zone, rng, 7, w=3, h=4, pad=1):
            gen.stamp(m, canopies[rng.randrange(3)], *spot)
        for spot in layout.zone_spots(fld, zone, rng, 3, w=1, h=3, pad=1):
            gen.stamp(m, cs.obj("umbrella_shut"), *spot)
        # water standing in the canopies that fell over, and never evaporating
        layout.glow_floor(m, fld, zone, t, "flow", ring(zone, 6, inset=4))
        fur.put("mushroom", zone.cx, zone.cy, pad=1)

    world.plan = fld
    world.landmarks = {"groves": [(z.cx, z.cy) for z in groves]}
    world.spawn = (groves[0].cx, groves[0].cy)
    world.npcs = ["umbrella_watcher", "drenched"]
    return world


def build_stars(map_id: int) -> World:
    """THE SHALLOWS.

    theme      an ocean of stars with a few boards laid across it
    feeling    walking on something that should not hold your weight
    layout     islands strung on a long pier, everything else unwalkable
    rule       leaving the boards is not possible, and the water is the sky
    """
    world, cs, rng = _new("stars", map_id, 144, 132)
    m, t = world.map, cs.tiles
    fld = Field(m.width, m.height)

    islands = layout.archipelago(fld, rng, islands=24, size=(15, 12), pier=3)
    # Second constraint: the islands are not variations on an island.  Each is
    # a different kind of place that happens to be surrounded by water.
    layout.vary_zones(islands, rng)
    for zone in islands:
        fld.carve(zone)
    centre = fld.carve(Zone("centre", m.width // 2, m.height // 2, 21, 15,
                            "round"))
    for zone in islands[::2]:
        fld.corridor((centre.cx, centre.cy), (zone.cx, zone.cy), width=3)
    fld.ensure_connected()
    fld.protect_chokepoints()
    fld.build_walls(2)
    layout.paint(m, fld, t, rng=rng)
    layout.shade_walls(m, fld, t)

    for index, zone in enumerate(islands):
        layout.carpet(m, fld, zone, t, rng,
                      ("rings", "full", "lattice", "corners")[index % 4])
        layout.glow_floor(m, fld, zone, t, "flow", ring(zone, 5, inset=3))
        gen.stamp(m, cs.obj("pier"), zone.cx - 2, zone.cy + 3)
        if index % 2 == 0:
            gen.stamp(m, cs.obj("lamp"), zone.cx + 5, zone.cy - 3)
        else:
            gen.stamp(m, cs.obj("pole"), zone.cx - 1, zone.cy - 4)
        for spot in layout.zone_spots(fld, zone, rng, 1, w=1, h=2, pad=1):
            gen.stamp(m, cs.obj("buoy"), *spot)
    gen.stamp_centered(m, cs.obj("island"), centre.cx, centre.cy)

    world.plan = fld
    world.landmarks = {"islands": [(z.cx, z.cy) for z in islands],
                       "centre": [(centre.cx, centre.cy)]}
    world.spawn = (islands[0].cx, islands[0].cy)
    world.npcs = ["ferryman", "lantern_bearer"]
    return world


BUILD = {
    "room": build_room, "nexus": build_nexus, "pink": build_pink,
    "numbers": build_numbers, "blocks": build_blocks, "stairs": build_stairs,
    "sand": build_sand, "faces": build_faces, "hands": build_hands,
    "checker": build_checker, "toys": build_toys, "neon": build_neon,
    "umbrellas": build_umbrellas, "stars": build_stars,
}


# How densely each dream carpets its floors, and with which arrangements.
# Sand stays nearly bare because its emptiness *is* the content; the nursery
# and the toy box are busy because a child decorated them.
CARPETS: dict[str, list[str]] = {
    "pink": ["full", "lattice", "rings", "checker", "cross"],
    "numbers": ["full", "lattice", "stripe", "checker", "rings"],
    "blocks": ["checker", "full", "rings", "lattice", "cross"],
    "stairs": ["stripe", "full", "lattice", "rings"],
    "sand": ["full", "rings", "lattice", "checker"],
    "faces": ["rings", "full", "lattice", "checker"],
    "hands": ["rings", "full", "cross", "lattice"],
    "checker": ["checker", "full", "lattice", "rings"],
    "toys": ["full", "checker", "rings", "lattice"],
    "umbrellas": ["rings", "lattice", "full", "checker"],
    "stars": ["rings", "full", "lattice"],
}

# The base flooring laid through every walkable tile of a world, before any
# room is dressed: (arrangement, period).  A smaller period is denser.
WASH: dict[str, tuple[str, int]] = {
    "pink": ("grid", 3), "numbers": ("diagonal", 3), "blocks": ("grid", 2),
    "stairs": ("rows", 2), "sand": ("scatter", 5), "faces": ("scatter", 4),
    "hands": ("diagonal", 4), "checker": ("grid", 2), "toys": ("grid", 3),
    "umbrellas": ("diagonal", 3), "stars": ("scatter", 4),
}

# Where the animated tiles go, and how many, per world.
GLOW: dict[str, tuple[str, int]] = {
    "pink": ("anim_0", 4), "numbers": ("anim_2", 6), "blocks": ("anim_1", 5),
    "stairs": ("flow", 8), "sand": ("anim_0", 2), "faces": ("anim_0", 6),
    "hands": ("anim_0", 4), "checker": ("anim_1", 6), "toys": ("anim_0", 6),
    "umbrellas": ("flow", 7), "stars": ("flow", 10),
}


def enforce_density(world: World) -> int:
    """Make sure no room is left as a wasteland.

    A large empty space is not atmosphere, it is an unfinished room.  This
    measures how much of each zone still shows bare ground and, where a zone
    is under-furnished for its size, adds more of that world's own props in a
    deliberate arrangement until it is not.  Corridors and their shoulders are
    still off limits, so filling can never block a route.
    """
    fld = world.plan
    if fld is None:
        return 0
    m, cs = world.map, world.chipset
    rng = random.Random(zlib.crc32(world.key.encode()) ^ 0xF111)
    bare = {cs.tiles[k] for k in ("ground", "ground_b", "path")
            if k in cs.tiles}
    props = [k for k, g in cs.objects.items()
             if not k.startswith(("mural_", "mark_")) and g.cols <= 4
             and g.rows <= 5 and k != "door"]
    if not props:
        return 0
    from .rooms import Furnisher, ring, avenue, corners, back_wall
    fur = Furnisher(m, fld, cs, rng)
    added = 0

    for zone in fld.zones:
        area = zone.w * zone.h
        if area < 200:
            continue
        # how much of this room is still nothing at all?
        empty = 0
        for dy in range(-zone.h // 2, zone.h // 2 + 1):
            for dx in range(-zone.w // 2, zone.w // 2 + 1):
                if (fld.is_floor(zone.cx + dx, zone.cy + dy)
                        and m.get_lower(zone.cx + dx, zone.cy + dy) in bare):
                    empty += 1
        if empty < area * 0.45:
            continue          # already furnished enough
        wanted = max(4, area // 90)
        spots = (ring(zone, wanted, inset=4) +
                 corners(zone, 5) +
                 avenue(zone, max(2, wanted // 3), spacing=6))
        for slot, (px, py) in enumerate(spots):
            if fur.put(props[(slot + zone.cx) % len(props)], px, py, pad=1):
                added += 1
    return added


def snap_spawn(world: World) -> None:
    """Move the arrival point onto ground the player can actually stand on.

    A builder picks a spawn from its own geometry — the centre of a terrace,
    the middle of an avenue — and decoration or a stepped zone shape can end
    up putting a wall there.  The player then arrives inside solid rock and
    the entire world reads as unreachable.  Search outward for real floor.
    """
    fld = world.plan
    if fld is None:
        return
    solid = solid_ids(world.chipset)
    m = world.map
    sx, sy = world.spawn

    def standable(x: int, y: int) -> bool:
        return (fld.is_floor(x, y)
                and (x % m.width, y % m.height) not in fld.sealed
                and m.get_lower(x, y) not in solid
                and m.get_upper(x, y) not in solid)

    if standable(sx, sy):
        return
    for radius in range(1, max(m.width, m.height) // 2):
        for dy in range(-radius, radius + 1):
            for dx in range(-radius, radius + 1):
                if max(abs(dx), abs(dy)) != radius:
                    continue
                if standable(sx + dx, sy + dy):
                    world.spawn = ((sx + dx) % m.width, (sy + dy) % m.height)
                    return


def place_door(world: World) -> None:
    """Stand one door in the world, at the point the player arrives.

    Every world has exactly one, and it is the same door in both directions:
    you come out of it and you go back through it.  Nothing else in a dream is
    an exit, so the way home is a place you have to find your way back to
    rather than a menu command — and the first thing you see on arriving is
    the thing you will eventually be looking for.

    The landing around it is cleared to bare floor so the door reads as
    deliberate rather than as something that grew there, and so a 2x3 solid
    object dropped into a generated layout cannot wall anything off.
    """
    if "door" not in world.chipset.objects:
        return
    m, fld = world.map, world.plan
    grid = world.chipset.obj("door")
    solid = solid_ids(world.chipset)

    def standable(x: int, y: int) -> bool:
        return (m.get_lower(x, y) not in solid
                and m.get_upper(x, y) not in solid)

    def fits(sx: int, sy: int) -> bool:
        """Is there already room here, without moving anything?"""
        # somewhere to stand, and somewhere to stand aside
        if not all(standable(sx + dx, sy) for dx in (-1, 0, 1)):
            return False
        for row in range(grid.rows):
            for col in range(grid.cols):
                x, y = sx - 1 + col, sy - grid.rows + row
                # the door's own space must be empty, and it must be standing
                # on floor rather than embedded in a wall or hanging over void
                if m.get_upper(x, y) != maps.EMPTY_UPPER:
                    return False
                if m.get_lower(x, y) in solid:
                    return False
                if fld is not None and fld.is_protected(x, y):
                    return False      # never block a corridor with a door
        return True

    sx, sy = world.spawn
    if not fits(sx, sy):
        # Look for a spot that already works.  The door does not get to clear
        # the ground it stands on — an object that bulldozes a rectangle of
        # plain floor out of a patterned world is exactly the thing this
        # project keeps having to un-learn.
        found = None
        for radius in range(1, 40):
            for dy in range(-radius, radius + 1):
                for dx in range(-radius, radius + 1):
                    if max(abs(dx), abs(dy)) != radius:
                        continue
                    if fits(sx + dx, sy + dy):
                        found = ((sx + dx) % m.width, (sy + dy) % m.height)
                        break
                if found:
                    break
            if found:
                break
        if found is None:
            return
        world.spawn = found
        sx, sy = found

    # the door stands with its base one tile above the arrival point
    dx, dy = sx - 1, sy - grid.rows
    gen.stamp(m, grid, dx, dy)
    # The door is solid, and the connectivity repair deletes solid things
    # standing on cells the layout calls floor — which is how the first version
    # of this ended up placing fourteen doors and shipping none of them.  A
    # door is a wall you can talk to, so the layout has to be told that.
    if fld is not None:
        for y in range(dy, dy + grid.rows):
            for x in range(dx, dx + grid.cols):
                fld.set(x % m.width, y % m.height, layout.WALL)
    world.landmarks["door"] = [(dx % m.width, dy % m.height)]
    # the tile you talk to it from is the one you are standing on
    world.landmarks["door_face"] = [((dx + 1) % m.width, (dy + grid.rows - 1) % m.height)]


def place_landmarks(world: World) -> None:
    """Drop each world's unique structures into its biggest rooms.

    Landmarks go where there is space for them and never near a corridor, and
    each one is used once — a landmark you meet twice is scenery.
    """
    fld = world.plan
    if fld is None:
        return
    marks = [k for k in world.chipset.objects if k.startswith("mark_")]
    if not marks:
        return
    m = world.map
    # biggest rooms first: a landmark needs room to be looked at
    zones = sorted(fld.zones, key=lambda z: z.w * z.h, reverse=True)
    used = 0
    for zone in zones:
        if used >= len(marks):
            break
        grid = world.chipset.obj(marks[used])
        x = zone.cx - grid.cols // 2
        y = zone.cy - grid.rows // 2
        if not fld.open_space(x, y, grid.cols, grid.rows, 1):
            continue
        gen.stamp(m, grid, x, y)
        world.landmarks.setdefault("marks", []).append((zone.cx, zone.cy))
        used += 1


def decorate(world: World) -> None:
    """Carpet every room, paint a mural in some, and set the floor glowing.

    Runs after a world's own builder, so each dream only has to describe its
    architecture and its props; the surface treatment is applied uniformly and
    tuned per world by the tables above.
    """
    fld = world.plan
    if fld is None or world.key not in CARPETS:
        return
    m, t = world.map, world.chipset.tiles
    rng = random.Random(zlib.crc32(world.key.encode()) ^ 0x5EED)
    # Base flooring across the whole world first, so corridors and the space
    # between rooms are treated too; room carpets then go on top of it.
    layout.floor_wash(m, fld, t, rng, period=WASH[world.key][1],
                      style=WASH[world.key][0])
    styles = CARPETS[world.key]
    anim, glow_count = GLOW.get(world.key, ("anim_0", 3))
    murals = [k for k in world.chipset.objects if k.startswith("mural_")]

    for index, zone in enumerate(fld.zones):
        layout.carpet(m, fld, zone, t, rng, styles[index % len(styles)])
        # one room in four gets a painting on its floor
        if murals and index % 4 == 1:
            grid = world.chipset.obj(murals[index % len(murals)])
            if fld.open_space(zone.cx - 2, zone.cy - 2, grid.cols, grid.rows, 0):
                gen.stamp(m, grid, zone.cx - 2, zone.cy - 2)
        if index % 3 == 0:
            from .rooms import ring as _ring
            layout.glow_floor(m, fld, zone, t, anim,
                              _ring(zone, glow_count, inset=4))


def build_all() -> dict[str, World]:
    """Generate every world, numbered in the order they are listed."""
    worlds: dict[str, World] = {}
    for index, key in enumerate(WORLD_ORDER, start=1):
        world = BUILD[key](index)
        decorate(world)
        place_landmarks(world)
        enforce_density(world)
        snap_spawn(world)
        if key in DREAM_ORDER:
            # after snap_spawn, so the door goes where the player really lands,
            # and before the connectivity repair, which gets the last word
            place_door(world)
        if world.plan is not None:
            # Last line of defence: nothing the decoration pass added is
            # allowed to have cut the world in half.
            repair_connectivity(world.map, world.plan, world.chipset,
                                world.spawn, world.chipset.tiles["ground"])
        worlds[key] = world
    return worlds
